collections:
  contributors:
    output: true
  lexicon:
    output: true
  definitions:
    output: true
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "lexicon"
    values:
      layout: "lemma"
  - scope:
      path: ""
      type: "definitions"
    values:
      layout: "definition"

scholar:
  bibliography: lexiconse.bib
  bibliography_template: bib
  relative: "../bibliography.html"
  sort_by: author, editor, year
  style: apa
  bibliography_list_tag:
  bibliography_item_tag: p

baseurl: /lexicon-scholarly-editing

plugins:
  - jekyll-last-modified-at
